// <auto-generated />
using System;
using Ataena.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ataena.Migrations
{
    [DbContext(typeof(AtaenaDbContext))]
    [Migration("20260226224947_AddNombreEmpresa")]
    partial class AddNombreEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ataena.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEmailEnviado")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCita")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrabajoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.HasIndex("TrabajoId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Ataena.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidosTutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .HasColumnType("TEXT");

                    b.Property<string>("DniTutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsVip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoDniPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoDniTutorPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreTutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoTutor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("[Dni] IS NOT NULL");

                    b.HasIndex("Nombre", "Apellidos");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Ataena.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupAutomaticoActivo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupCopiarAutomaticamenteNube")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupFrecuencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupHora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupMantenerUltimos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupRutaNube")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackupServicioNube")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdiomaApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEstudio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPuerto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpServidor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmtpUsarSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemaOscuro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackupAutomaticoActivo = false,
                            BackupCopiarAutomaticamenteNube = true,
                            BackupFrecuencia = 0,
                            BackupHora = 840,
                            BackupMantenerUltimos = 10,
                            Direccion = "Calle Núñez de Reinoso, Guadalajara",
                            IdiomaApp = "es",
                            NombreEstudio = "Estudio Erzulie",
                            SmtpPuerto = 587,
                            SmtpUsarSsl = true,
                            TemaOscuro = true
                        });
                });

            modelBuilder.Entity("Ataena.Models.Consentimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConsentimientoRenovacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DniTutorFirmante")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EdadClienteAlFirmar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsConsentimientoMenor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaMenorBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaTutorBase64")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Firmado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreTutorFirmante")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Renovado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaDocumento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrabajoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Tipo");

                    b.HasIndex("TrabajoId")
                        .IsUnique();

                    b.ToTable("Consentimientos");
                });

            modelBuilder.Entity("Ataena.Models.DiaFestivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoSubdivision")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsFijo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPersonalizado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreIngles")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Fecha");

                    b.HasIndex("Fecha", "Nombre")
                        .IsUnique();

                    b.ToTable("DiasFestivos");
                });

            modelBuilder.Entity("Ataena.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Colores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracionEstimadaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DuracionRealMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estilo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoAntesPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoDespuesPath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Fotos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotosJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tamano")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZonaCuerpo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Fecha");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("Ataena.Models.Cita", b =>
                {
                    b.HasOne("Ataena.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ataena.Models.Trabajo", "Trabajo")
                        .WithMany("Citas")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Ataena.Models.Consentimiento", b =>
                {
                    b.HasOne("Ataena.Models.Cliente", "Cliente")
                        .WithMany("Consentimientos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ataena.Models.Trabajo", "Trabajo")
                        .WithOne("Consentimiento")
                        .HasForeignKey("Ataena.Models.Consentimiento", "TrabajoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Ataena.Models.Trabajo", b =>
                {
                    b.HasOne("Ataena.Models.Cliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ataena.Models.Cliente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Consentimientos");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Ataena.Models.Trabajo", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Consentimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
